# 项目相关配置
ruoyi:
  # 名称
  name: RockBurst
  # 版本
  version: 3.8.8
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /home/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn
# Minio配置
#minio:
#  endpoint: ${miniourl:http://47.92.215.128:19000}
#  accessKey: ${minioakey:9nLLPYeJs3CX1jj3GC1r}
#  secretKey: ${minioskey:finms5hOxZXwc6ZfUfVV5qPpfazIRNibN7PH1erG}
#  defaultBucketName: ${miniobname:bust-dev} #存储桶名称
# Minio配置
minio:
  endpoint: ${miniourl:http://124.221.117.118:19000}
  accessKey: ${minioakey:jh1wTyqzqWQ8KxsvtTIi}
  secretKey: ${minioskey:4LAQfrsrAhgYVhMrmWgL5c25jZWT9rcPQxNBvoOG}
  defaultBucketName: ${miniobname:bust-dev} #存储桶名称

#MQTT配置信息
mqtt:
  host: tcp://47.104.160.255:1883
  clientid: mqttjs_cloud7
  username: dingyue
  password: 123456
  timeout: 10
  keepalive: 20
  topic: /iot/data2
  # 可以明确配置，不配置则使用代码中的默认值 false
  clean-session: false



#file:
#  bucketName: bust-dev
#  oss:
#    accessKey: 9nLLPYeJs3CX1jj3GC1r
#    secretKey: finms5hOxZXwc6ZfUfVV5qPpfazIRNibN7PH1erG
#    endpoint: http://47.92.215.128:19000
# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      enabled: true
      # 单个文件大小
      max-file-size: 500MB
      # 设置总上传的文件大小
      max-request-size: 1024MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: false
  elasticsearch:
    rest:
      uris: 192.168.31.156:9200

easy-es:
  enable: true
  address: 192.168.31.156:9200
  global-config:
    print-dsl: true
    process_index_mode: manual
    enable-index-alias: false

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 7200

# MyBatis Plus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

springdoc:
  api-docs:
    path: /openapi/v3/api-docs

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
